[book]
authors = ["phoenixr-codes"]
language = "en"
multilingual = false
src = "src"
title = "mdbook-inline-highlighting"

[preprocessor.inline-highlighting]
after = ["links"]
default-language = "javascript"